{
 "button":[
 {
       "name":"报修信息",
       "sub_button":[
        {
           "type":"view",
           "name":"查询工单",
           "url":"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx90dfbf42a2cdaa4a&redirect_uri=http://mvsengineertaskhelper.duapp.com/wxAuth2&response_type=code&scope=snsapi_base&state=myOrder#wechat_redirect"
        },
        {
           "type":"click",
           "name":"到场签到",
           "key":"OnSite"
        },
        {
           "type":"click",
           "name":"离场",
           "key":"OffSite"
        },
        {
            "type":"click",
            "name":"上传图片",
            "key":"UploadPic"
         },
        {
           "type":"click",
           "name":"报修统计",
           "key":"MyStatics"
        }
        ]
  },
  {
       "name":"业务数据",
       "sub_button":[
        {
           "type":"click",
           "name":"上班打卡",
           "key":"Login"
        },
        {
           "type":"click",
           "name":"下班打卡",
           "key":"Logout"
        },
        {
           "type":"view",
           "name":"我的打卡纸",
           "url":"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx90dfbf42a2cdaa4a&redirect_uri=http://mvsengineertaskhelper.duapp.com/wxAuth2&response_type=code&scope=snsapi_base&state=mySign#wechat_redirect"
        },
        {
           "type":"click",
           "name":"登录信息",
           "key":"MyInfo"
        }]
   },
   {
       
       "name":"基础数据",
       "sub_button":[
       {
          "type":"view",
          "name":"知识库",
          "url":"http://124.74.9.202:7816/"
       },
       {
    	   "type":"view",
           "name":"通讯录",
           "url":"http://mvsengineertaskhelper.duapp.com/contacts.html"
        },
        {
            "type":"view",
            "name":"店铺信息",
            "url":"http://124.74.9.202:7816/"
         }]
   }]
}